version: "3.4"
services:

  mysite:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: mysite
    restart: unless-stopped
    ports:
      - 4080:80
    volumes:
      - ./:/var/www/test

  c2:
    image: codeception/codeception
    volumes:
      - .:/project